name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.15.0'

      - name: Install dependencies (if needed)
        run: npm ci

      - name: Build the project (if needed)
        run: npm run build

      - name: Copy files to deploy directory
        run: |
          mkdir gh-pages  
          cp -r src/* gh-pages/  

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Token para autenticación automática
          publish_dir: gh-pages  # Desplegar el contenido de gh-pages
